name: build

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  merge-and-deploy:
    name: Merge dev to main & Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set Git user for the merge commit
      - name: Set Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Merge dev branch into main
      - name: Merge branches
        run: |
          git checkout main
          git pull origin main
          git merge dev
          git push origin main

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      # Set Yarn version
      - name: Set Yarn Version
        id: set-version
        run: |
          yarn set version 4.3.1
          echo "YARN_VERSION=$(yarn -v)" >> $GITHUB_OUTPUT

      # Cache dependencies
      - name: Yarn Cache - PnP
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ steps.set-version.outputs.YARN_VERSION }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      # Build the project
      - name: Build project
        run: yarn build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
